name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: ["master"]

jobs:

  linux-windows-build:
    name: CSharp Build
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: windows-latest
    timeout-minutes: 45
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
  
    - name: Download Tools
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
        Invoke-WebRequest -Uri https://github.com/aead/minisign/releases/download/v0.2.0/minisign-windows-amd64.zip -OutFile minisign-windows-amd64.zip
        New-Item -Path "." -Name "minisign" -ItemType "directory"
        Expand-Archive -LiteralPath 'minisign-windows-amd64.zip' -DestinationPath 'minisign'
        Remove-Item -Path minisign-windows-amd64.zip

    - name: Check out code
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: MSBuild
      run: |
        msbuild.exe Rubeus.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=compiled/

    - name: Build Package
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        cat alias.json | jq ".version |= \"$VERSION\"" > ./compiled/alias.json
        cp LICENSE ./compiled/LICENSE
        cd compiled
        tar -czvf ../rubeus.tar.gz .
      
    - name: Sign Package
      run: |
        echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > minisign.key
        MANIFEST=$(cat ./compiled/alias.json | base64 -w 0)
        bash -c "echo \"\" | ~/minisign -s minisign.key -S -m ./rubeus.tar.gz -t \"$MANIFEST\" -x rubeus.minisig"

    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./rubeus.minisig
          ./rubeus.tar.gz
